
name: Docker Image CI
on:
  pull_request:
  push:
    branches-ignore: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install goss and dgoss
        uses: e1himself/goss-installation-action@v1
        with:
          # Goss release version to install
          version: 'v0.3.13'
      - uses: actions/checkout@v2
      - name: install buildx
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Build the Docker image
        run: make build-docker-image
      - name: Run goss tests
        run: make dgoss-ci
