
name: Docker Image CI
on:
  push:
    branches-ignore: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install goss and dgoss
        uses: e1himself/goss-installation-action@v1
        with:
          # Goss release version to install
          version: 'v0.3.9'
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hyzual/koel-dev:latest
      - name: Run goss tests
        run: dgoss run hyzual/koel-dev:latest
