name: Docker Hub publish
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install goss and dgoss
        uses: e1himself/goss-installation-action@v1
        with:
          # Goss release version to install
          version: 'v0.3.13'
      - uses: actions/checkout@v2
      - name: Build the x86_64 Docker image
        run: make build-docker-image
      - name: Run goss tests on x86_64 image
        run: make dgoss-ci
      - name: Push the Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hyzual/koel
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
