name: Run tests and deploy image
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install goss and dgoss
        uses: e1himself/goss-installation-action@v1
        with:
          # Goss release version to install
          version: "v0.3.13"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the x86_64 Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          push: false
          tags: latest
      - name: Run goss tests on x86_64 image
        run: make dgoss-ci
      - name: Build and push production image
        uses: zmingxie/docker_buildx@v1.1
        with:
          publish: true
          imageName: hyzual/koel
          dockerHubUser: ${{ secrets.DOCKER_HUB_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
